In [107]:
from __future__ import annotations
import sys
from pathlib import Path

import pandas as pd

## [1] 데이터 불러오기

In [108]:
excel_path = Path(r"G:\service_order_02.xlsx")
df = pd.read_excel(excel_path, sheet_name=0)
df

,서비스처리센터,고객방문일,고객방문시간,우선순위,오더번호,상태,대분류,중분류,소분류,내역,...,기사배정시간,배정된기사,마감일,마감시간,마감자,변경일,변경시간,변경자,수수료금액,영수증번호
0,H051,2026.02.09,17:30:00,2,28522542,처리완료,요금,수납/환불,환불,[요금 수정 후 환불 등록] 61870*******2855 국민 서윤주,...,00:00:00,NaN,2026.02.09,11:16:06,CSC7315,2026.02.09,11:16:06,CSC7315,NaN,NaN
1,H051,2026.02.04,15:00:00,2,28509918,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **순,...,09:35:50,김현남,2026.02.04,15:10:44,김민지,2026.02.04,15:10:44,MOBILE,"79,000",H051-028-20260204-S150946
2,H051,2026.02.03,15:00:00,2,28507988,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **현,...,13:05:35,김현남,2026.02.03,15:20:32,강아람,2026.02.03,15:20:32,MOBILE,"79,000",H051-028-20260203-S152026
3,H051,2026.02.04,10:21:00,2,28510237,처리완료,서비스,계량기/안전,타이머,어제 가스렌지 교체후 사용할려고 하니깐 안전타이머가 2초도 안되서 바로,...,10:37:25,김현남,2026.02.04,10:50:32,김민지,2026.02.04,10:50:32,MOBILE,0,NaN
4,H051,2026.02.02,10:00:00,2,28502636,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **옥,...,16:32:35,김현남,2026.02.02,10:17:14,김민지,2026.02.02,10:17:14,MOBILE,"79,000",H051-028-20260202-S101637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64905,H075,2026.02.25,17:06:00,2,28573643,처리완료,요금,요금,검침,검침관련문의 010********** **명)***,...,00:00:00,NaN,2026.02.25,17:14:58,CSC7509,2026.02.25,17:14:58,CSC7509,NaN,NaN
64906,H075,2026.02.24,17:46:00,2,28569492,처리완료,요금,요금,검침,원격검침 오류로 인한 지침 수정 재고지,...,00:00:00,NaN,2026.02.24,17:47:28,CSC7509,2026.02.24,17:47:28,CSC7509,NaN,NaN
64907,H075,2026.02.24,16:56:00,2,28569188,처리완료,요금,요금,검침,검침관련 010********** **모,...,00:00:00,NaN,2026.02.24,17:52:24,CSC7509,2026.02.24,17:52:24,CSC7509,NaN,NaN
64908,H075,2026.02.25,14:24:00,2,28572405,처리완료,요금,요금,검침,검침원관련 010********** **아,...,00:00:00,NaN,2026.02.25,14:29:37,CSC7517,2026.02.25,14:29:37,CSC7517,NaN,NaN
64909,H075,2026.02.26,16:42:00,2,28577607,처리완료,요금,요금,검침,검침관련 6353-4275 형유미 주택관리,...,00:00:00,NaN,2026.02.26,17:16:16,CSC7505,2026.02.26,17:16:16,CSC7505,NaN,NaN

## [2] 데이터 확인

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64910 entries, 0 to 64909
Data columns (total 38 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   서비스처리센터    64910 non-null  object
 1   고객방문일      64910 non-null  object
 2   고객방문시간     64910 non-null  object
 3   우선순위       64910 non-null  int64
 4   오더번호       64910 non-null  int64
 5   상태         64910 non-null  object
 6   대분류        64910 non-null  object
 7   중분류        64910 non-null  object
 8   소분류        64910 non-null  object
 9   내역         64909 non-null  object
 10  세대         64910 non-null  int64
 11  고객서비스처리센터  64910 non-null  object
 12  고객번호       61607 non-null  float64
 13  계약계정번호     61607 non-null  float64
 14  정보         19517 non-null  object
 15  정보(BP)     19514 non-null  object
 16  최초공급일      53904 non-null  object
 17  주소         64842 non-null  object
 18  건물동        15736 non-null  object
 19  호수         64801 non-null  object
 20  전입/전출일     48091 non-null  object
 21  오더생성일      64910 non-null  object
 22  오더생성시간     64910 non-null  object
 23  오더생성자      64910 non-null  object
 24  부서확인일      64884 non-null  object
 25  부서확인시간     64910 non-null  object
 26  부서확인자      64884 non-null  object
 27  기사배정일      53133 non-null  object
 28  기사배정시간     64910 non-null  object
 29  배정된기사      53133 non-null  object
 30  마감일        64910 non-null  object
 31  마감시간       64910 non-null  object
 32  마감자        64732 non-null  object
 33  변경일        64886 non-null  object
 34  변경시간       64910 non-null  object
 35  변경자        64886 non-null  object
 36  수수료금액      58589 non-null  object
 37  영수증번호      2263 non-null   object
dtypes: float64(2), int64(3), object(33)
memory usage: 18.8+ MB

In [110]:
address_col = df.columns[17]
df[address_col].value_counts()

주소
둔산로65번길 43 (둔산동 1336)                 258
온천로 45 (봉명동 536-8 푸르지오시티)             241
신도안면 신도안3길 55 (남선리 1340 계룡대해미르아파트)    194
은구비남로 34 (노은동 520-1 열매마을)             151
계족로664번길 27 (법동 188 한마음아파트)           141
                                     ...
신성남로95번길 64 (신성동 142-14)                1
계룡로59번길 8 (봉명동 444-16)                  1
신성남로 35 (신성동 253-38)                    1
도안북로118번길 4 (도안동 964)                   1
온천북로33번길 36-37 (봉명동 641-10)             1
Name: count, Length: 13041, dtype: int64

### (1) 검증용 행정동 리스트 활성

In [111]:
locations = [
    "엄사면", "금암동", "신도안면", "두마면", "갈마동", "둔산동", "만년동", "월평동", "탄방동", "봉산동",
    "덕암동", "중리동", "전민동", "용전동", "비래동", "목상동", "오정동", "대화동", "신탄진동", "상서동",
    "홍도동", "송강동", "법동", "문평동", "송촌동", "연축동", "도룡동", "석봉동", "신일동", "화암동",
    "와동", "문지동", "읍내동", "평촌동", "가정동", "원촌동", "신대동", "덕진동", "관평동", "용산동",
    "탑립동", "금고동", "신동", "구룡동", "둔곡동", "유천동", "괴정동", "가장동", "복수동", "태평동",
    "변동", "내동", "관저동", "도마동", "원내동", "산성동", "가수원동", "용문동", "정림동", "사정동",
    "방동", "괴곡동", "안영동", "자양동", "용운동", "가양동", "대동", "문화동", "가오동", "대흥동",
    "중촌동", "정동", "오류동", "판암동", "목동", "선화동", "용두동", "대사동", "효동", "석교동",
    "성남동", "삼성동", "옥계동", "중동", "호동", "인동", "부사동", "천동", "은행동", "대성동",
    "문창동", "낭월동", "신흥동", "원동", "삼정동", "신안동", "소제동", "구도동", "세천동", "비룡동",
    "대별동", "신성동", "장대동", "지족동", "궁동", "봉명동", "구암동", "노은동", "추목동", "어은동",
    "장동", "구성동", "자운동", "신봉동", "죽동", "상대동", "방현동", "대정동", "반석동", "하기동",
    "교촌동", "덕명동", "원신흥동", "수남동", "외삼동", "도안동", "계산동", "용계동", "복용동", "학하동",
    "갑동"
]

In [112]:
cnt = pd.Series(locations).value_counts()
cnt

엄사면     1
금암동     1
신도안면    1
두마면     1
갈마동     1
       ..
계산동     1
용계동     1
복용동     1
학하동     1
갑동      1
Name: count, Length: 131, dtype: int64

In [113]:
duple = cnt[cnt>1]
duple

Series([], Name: count, dtype: int64)

## [3] 주소 형태소 분석

In [114]:
df['주소'].value_counts()

주소
둔산로65번길 43 (둔산동 1336)                 258
온천로 45 (봉명동 536-8 푸르지오시티)             241
신도안면 신도안3길 55 (남선리 1340 계룡대해미르아파트)    194
은구비남로 34 (노은동 520-1 열매마을)             151
계족로664번길 27 (법동 188 한마음아파트)           141
                                     ...
신성남로95번길 64 (신성동 142-14)                1
계룡로59번길 8 (봉명동 444-16)                  1
신성남로 35 (신성동 253-38)                    1
도안북로118번길 4 (도안동 964)                   1
온천북로33번길 36-37 (봉명동 641-10)             1
Name: count, Length: 13041, dtype: int64

In [115]:
df

,서비스처리센터,고객방문일,고객방문시간,우선순위,오더번호,상태,대분류,중분류,소분류,내역,...,기사배정시간,배정된기사,마감일,마감시간,마감자,변경일,변경시간,변경자,수수료금액,영수증번호
0,H051,2026.02.09,17:30:00,2,28522542,처리완료,요금,수납/환불,환불,[요금 수정 후 환불 등록] 61870*******2855 국민 서윤주,...,00:00:00,NaN,2026.02.09,11:16:06,CSC7315,2026.02.09,11:16:06,CSC7315,NaN,NaN
1,H051,2026.02.04,15:00:00,2,28509918,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **순,...,09:35:50,김현남,2026.02.04,15:10:44,김민지,2026.02.04,15:10:44,MOBILE,"79,000",H051-028-20260204-S150946
2,H051,2026.02.03,15:00:00,2,28507988,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **현,...,13:05:35,김현남,2026.02.03,15:20:32,강아람,2026.02.03,15:20:32,MOBILE,"79,000",H051-028-20260203-S152026
3,H051,2026.02.04,10:21:00,2,28510237,처리완료,서비스,계량기/안전,타이머,어제 가스렌지 교체후 사용할려고 하니깐 안전타이머가 2초도 안되서 바로,...,10:37:25,김현남,2026.02.04,10:50:32,김민지,2026.02.04,10:50:32,MOBILE,0,NaN
4,H051,2026.02.02,10:00:00,2,28502636,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **옥,...,16:32:35,김현남,2026.02.02,10:17:14,김민지,2026.02.02,10:17:14,MOBILE,"79,000",H051-028-20260202-S101637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64905,H075,2026.02.25,17:06:00,2,28573643,처리완료,요금,요금,검침,검침관련문의 010********** **명)***,...,00:00:00,NaN,2026.02.25,17:14:58,CSC7509,2026.02.25,17:14:58,CSC7509,NaN,NaN
64906,H075,2026.02.24,17:46:00,2,28569492,처리완료,요금,요금,검침,원격검침 오류로 인한 지침 수정 재고지,...,00:00:00,NaN,2026.02.24,17:47:28,CSC7509,2026.02.24,17:47:28,CSC7509,NaN,NaN
64907,H075,2026.02.24,16:56:00,2,28569188,처리완료,요금,요금,검침,검침관련 010********** **모,...,00:00:00,NaN,2026.02.24,17:52:24,CSC7509,2026.02.24,17:52:24,CSC7509,NaN,NaN
64908,H075,2026.02.25,14:24:00,2,28572405,처리완료,요금,요금,검침,검침원관련 010********** **아,...,00:00:00,NaN,2026.02.25,14:29:37,CSC7517,2026.02.25,14:29:37,CSC7517,NaN,NaN
64909,H075,2026.02.26,16:42:00,2,28577607,처리완료,요금,요금,검침,검침관련 6353-4275 형유미 주택관리,...,00:00:00,NaN,2026.02.26,17:16:16,CSC7505,2026.02.26,17:16:16,CSC7505,NaN,NaN

In [116]:
address_col = df.columns[17]
addr = df[address_col].astype("string")

paren = addr.str.extract(r"\(([^)]*)\)", expand=False)

pattern = r"([가-힣][가-힣0-9-]*[동면])(?=\s|$)"

in_paren = (
    paren
    .str.extract(pattern, expand=False)
    .str.replace(r"[^가-힣]", "", regex=True)
)

addr_outside_paren = addr.str.replace(r"\([^)]*\)", "", regex=True)
in_addr = (
    addr_outside_paren
    .str.extract(pattern, expand=False)
    .str.replace(r"[^가-힣]", "", regex=True)
)

df["행정동"] = in_paren.fillna(in_addr)

In [117]:
df[df["행정동"].notna()]

,서비스처리센터,고객방문일,고객방문시간,우선순위,오더번호,상태,대분류,중분류,소분류,내역,...,배정된기사,마감일,마감시간,마감자,변경일,변경시간,변경자,수수료금액,영수증번호,행정동
0,H051,2026.02.09,17:30:00,2,28522542,처리완료,요금,수납/환불,환불,[요금 수정 후 환불 등록] 61870*******2855 국민 서윤주,...,NaN,2026.02.09,11:16:06,CSC7315,2026.02.09,11:16:06,CSC7315,NaN,NaN,신도안면
1,H051,2026.02.04,15:00:00,2,28509918,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **순,...,김현남,2026.02.04,15:10:44,김민지,2026.02.04,15:10:44,MOBILE,"79,000",H051-028-20260204-S150946,두마면
2,H051,2026.02.03,15:00:00,2,28507988,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **현,...,김현남,2026.02.03,15:20:32,강아람,2026.02.03,15:20:32,MOBILE,"79,000",H051-028-20260203-S152026,금암동
3,H051,2026.02.04,10:21:00,2,28510237,처리완료,서비스,계량기/안전,타이머,어제 가스렌지 교체후 사용할려고 하니깐 안전타이머가 2초도 안되서 바로,...,김현남,2026.02.04,10:50:32,김민지,2026.02.04,10:50:32,MOBILE,0,NaN,엄사면
4,H051,2026.02.02,10:00:00,2,28502636,처리완료,서비스,계량기/안전,타이머,[타이머설치] 010********** **옥,...,김현남,2026.02.02,10:17:14,김민지,2026.02.02,10:17:14,MOBILE,"79,000",H051-028-20260202-S101637,두마면
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64905,H075,2026.02.25,17:06:00,2,28573643,처리완료,요금,요금,검침,검침관련문의 010********** **명)***,...,NaN,2026.02.25,17:14:58,CSC7509,2026.02.25,17:14:58,CSC7509,NaN,NaN,상대동
64906,H075,2026.02.24,17:46:00,2,28569492,처리완료,요금,요금,검침,원격검침 오류로 인한 지침 수정 재고지,...,NaN,2026.02.24,17:47:28,CSC7509,2026.02.24,17:47:28,CSC7509,NaN,NaN,지족동
64907,H075,2026.02.24,16:56:00,2,28569188,처리완료,요금,요금,검침,검침관련 010********** **모,...,NaN,2026.02.24,17:52:24,CSC7509,2026.02.24,17:52:24,CSC7509,NaN,NaN,지족동
64908,H075,2026.02.25,14:24:00,2,28572405,처리완료,요금,요금,검침,검침원관련 010********** **아,...,NaN,2026.02.25,14:29:37,CSC7517,2026.02.25,14:29:37,CSC7517,NaN,NaN,지족동
64909,H075,2026.02.26,16:42:00,2,28577607,처리완료,요금,요금,검침,검침관련 6353-4275 형유미 주택관리,...,NaN,2026.02.26,17:16:16,CSC7505,2026.02.26,17:16:16,CSC7505,NaN,NaN,신성동

In [123]:
df.loc[df["주소"].str.contains("유동", na=False), ["주소", "행정동"]].head()

                                  주소  행정동
15      엄사면 번영3길 91 (유동리 14-6 대동아파트)  엄사면
23      엄사면 번영3길 91 (유동리 14-6 대동아파트)  엄사면
25      엄사면 번영3길 91 (유동리 14-6 대동아파트)  엄사면
26      엄사면 번영3길 91 (유동리 14-6 대동아파트)  엄사면
28  엄사면 계백로 3051 (유동리 460 계룡블루힐스아파트)  엄사면

In [119]:
df[df["행정동"].isna()]

,서비스처리센터,고객방문일,고객방문시간,우선순위,오더번호,상태,대분류,중분류,소분류,내역,...,배정된기사,마감일,마감시간,마감자,변경일,변경시간,변경자,수수료금액,영수증번호,행정동
1241,H051,2026.02.05,17:48:00,2,28515541,처리완료,서비스,기타,민원수수료 취소,[민원수수료 취소] 원오더 : 28507988,...,NaN,2026.02.05,17:49:26,이혜인,2026.02.05,17:50:04,CSC7306,0,NaN,<NA>
7923,H071,2026.02.05,19:00:00,2,28512415,처리완료,요금,자동이체,자동-오류,자동이체신청오류 / 외국인분으로 업무폰에서 문자보냄,...,NaN,2026.02.05,09:29:19,CSC7115,2026.02.05,09:29:19,CSC7115,0,NaN,<NA>
7924,H071,2026.02.05,19:00:00,2,28512413,처리완료,요금,자동이체,자동-오류,자동이체신청오류,...,NaN,2026.02.05,09:31:09,CSC7105,2026.02.05,09:31:09,CSC7105,0,NaN,<NA>
7925,H071,2026.02.04,19:04:00,2,28509559,처리완료,요금,자동이체,자동-오류,자동이체신청오류//재등록 완료,...,NaN,2026.02.04,09:45:30,CSC7105,2026.02.04,09:45:30,CSC7105,0,NaN,<NA>
7926,H071,2026.02.05,19:00:00,2,28512417,처리완료,요금,자동이체,자동-오류,자동이체신청오류-1차 연락시 통화중이심/2차 전화안받으셔서 문자 넣음/3,...,NaN,2026.02.05,13:14:03,CSC7104,2026.02.05,13:14:03,CSC7104,0,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63609,H075,2026.02.10,15:00:00,2,28526685,처리완료,요금,요금,공급중지,[공급중단/체납],...,박종범,2026.02.10,12:06:55,박종범,2026.02.10,12:06:55,MOBILE,0,NaN,<NA>
63610,H075,2026.02.10,15:00:00,2,28526686,처리완료,요금,요금,공급중지,[공급중단/체납],...,박종범,2026.02.10,12:19:15,박종범,2026.02.10,12:19:15,MOBILE,0,NaN,<NA>
63616,H075,2026.02.10,15:00:00,2,28526684,처리완료,요금,요금,공급중지,[공급중단/체납],...,박종범,2026.02.10,11:43:49,박종범,2026.02.10,11:43:49,MOBILE,0,NaN,<NA>
63629,H075,2026.02.10,15:00:00,2,28526683,처리완료,요금,요금,공급중지,[공급중단/체납],...,박종범,2026.02.10,11:18:46,박종범,2026.02.10,11:18:46,MOBILE,0,NaN,<NA>
63645,H075,2026.02.10,15:00:00,2,28526688,처리완료,요금,요금,공급중지,[공급중단/체납],...,박종범,2026.02.10,13:34:01,박종범,2026.02.10,13:34:01,MOBILE,0,NaN,<NA>

In [120]:
# df.to_excel("2026.02_서비스오더_수정.xlsx", index=False)

In [121]:
df['행정동'].value_counts()

행정동
자양동    4135
도마동    3643
가양동    3412
갈마동    2993
봉명동    2558
       ...
소제동       2
화암동       1
원촌동       1
방동        1
장동        1
Name: count, Length: 121, dtype: Int64

In [122]:
df["행정동_정합성"] = df["행정동"].isin(locations)

# 결과 요약
print(df["행정동_정합성"].value_counts(dropna=False))

# locations에 없는 행정동만 보기
invalid_df = df[~df["행정동"].isin(locations)]

print(len(invalid_df))
print(invalid_df[["행정동"]].drop_duplicates().sort_values("행정동"))

행정동_정합성
True     64842
False       68
Name: count, dtype: int64
68
       행정동
1241  <NA>

In [125]:
address_col = df.columns[17]
addr = df[address_col].astype("string")

suspect_pattern = r"동로|동길|동리|면로|면길|읍로|읍길|아파트동|상가동|제\d+동|,|/|-"

df_suspect = df[addr.str.contains(suspect_pattern, na=False, regex=True)]

print(len(df_suspect))
print(df_suspect[[address_col, "행정동"]].head(30))

50722
                                    주소   행정동
3            엄사면 번영8길 8-11 (엄사리 266-3)   엄사면
10              엄사면 전원로 38 (엄사리 123-7)   엄사면
12          두마면 입암길 41-4 (입암리 29 세화주택)   두마면
13    엄사면 엄사중앙로 65-9 (엄사리 367 두산신성아파트)   엄사면
15        엄사면 번영3길 91 (유동리 14-6 대동아파트)   엄사면
17          두마면 입암길 41-4 (입암리 29 세화주택)   두마면
18              서금암2길 19-4 (금암동 148-7)   금암동
20          엄사면 전원1길 17-5 (엄사리 170-10)   엄사면
21       서금암4길 6-9 (금암동 69-1 주공2단지아파트)   금암동
23        엄사면 번영3길 91 (유동리 14-6 대동아파트)   엄사면
25        엄사면 번영3길 91 (유동리 14-6 대동아파트)   엄사면
26        엄사면 번영3길 91 (유동리 14-6 대동아파트)   엄사면
27         엄사면 번영3길 73-17 (엄사리 226-41)   엄사면
28    엄사면 계백로 3051 (유동리 460 계룡블루힐스아파트)   엄사면
31               서금암2길 7-9 (금암동 156-4)   금암동
33    엄사면 번영3길 73-12 (엄사리 226-4 삼진아파트)   엄사면
34    엄사면 번영로 113-32 (엄사리 587 계룡 파라디아)   엄사면
36                 장안1길 32 (금암동 181-4)   금암동
40  두마면 사계로 51 (두계리 116 계룡대림e-편한세상아파트)   두마면
45                 장안2길 42 (금암동 176-8)   금암동
50             신도안면 부남리 사서함 501-50 계룡대  신도안면
52                 장안1길 32 (금암동 181-4)   금암동
53           장안로 75 (금암동 167-1 우림루미아트)   금암동
54           장안로 75 (금암동 167-1 우림루미아트)   금암동
55    엄사면 엄사중앙로 65-9 (엄사리 367 두산신성아파트)   엄사면
56    엄사면 번영3길 73-12 (엄사리 226-4 삼진아파트)   엄사면
58    엄사면 번영3길 73-12 (엄사리 226-4 삼진아파트)   엄사면
59              엄사면 번영로 70 (엄사리 253-4)   엄사면
61               장안로 59-15 (금암동 164-1)   금암동
62          서금암3길 5 (금암동 146-9 쉐리움아파트)   금암동